# NumPy — Guía Práctica Completa

## ¿Qué es NumPy?

**NumPy** (Numerical Python) es la librería fundamental para cálculo numérico en Python.
Casi todo el ecosistema científico de Python (Pandas, Matplotlib, Scikit-learn, SciPy)
está construido sobre NumPy.

## ¿Por qué necesitamos NumPy si ya tenemos listas?

Excelente pregunta. Veamos el problema con un ejemplo concreto.

Imagina que tienes las temperaturas de 5 días y quieres convertirlas de Celsius a Fahrenheit
usando la fórmula `F = C * 9/5 + 32`.

**Con una lista de Python** necesitas un ciclo `for`:

In [2]:
# Con lista de Python — necesitas un ciclo
celsius_lista = [0, 20, 37, 100, -10]
fahrenheit_lista = []

for c in celsius_lista:
    fahrenheit_lista.append(c * 9/5 + 32)

print('Fahrenheit (con lista):', fahrenheit_lista)

Fahrenheit (con lista): [32.0, 68.0, 98.6, 212.0, 14.0]


In [3]:
import numpy as np

# Con NumPy — sin ciclos, más rápido y más legible
celsius_array = np.array([0, 20, 37, 100, -10])
fahrenheit_array = celsius_array * 9/5 + 32

print('Fahrenheit (con NumPy):', fahrenheit_array)
print(f'\nVersión de NumPy: {np.__version__}')

Fahrenheit (con NumPy): [ 32.   68.   98.6 212.   14. ]

Versión de NumPy: 2.4.2


El resultado es el mismo, pero NumPy es:
- **Más legible**: la operación matemática se ve igual que la fórmula
- **Más rápido**: para millones de datos, NumPy puede ser 100x más rápido que un ciclo Python
- **Más compacto**: una línea en lugar de cuatro

Veamos la diferencia de velocidad con datos grandes:

In [4]:
import time

N = 1_000_000  # un millón de datos
datos_lista = list(range(N))
datos_array = np.arange(N, dtype=float)

# Con lista y ciclo for
inicio = time.time()
resultado_lista = [x * 2 + 1 for x in datos_lista]
tiempo_lista = time.time() - inicio

# Con NumPy
inicio = time.time()
resultado_array = datos_array * 2 + 1
tiempo_numpy = time.time() - inicio

print(f'Lista (for loop): {tiempo_lista:.4f} segundos')
print(f'NumPy array:      {tiempo_numpy:.4f} segundos')
print(f'NumPy es {tiempo_lista/tiempo_numpy:.0f}x más rápido')

Lista (for loop): 0.0534 segundos
NumPy array:      0.0038 segundos
NumPy es 14x más rápido


## ¿Cuándo usar NumPy?

| Situación | ¿Usar NumPy? |
|---|---|
| Cálculos matemáticos sobre colecciones de números | ✅ Sí |
| Álgebra lineal (matrices, vectores) | ✅ Sí |
| Estadísticas (media, desviación, etc.) | ✅ Sí |
| Guardar objetos mixtos (strings + números) | ❌ Usa lista o Pandas |
| Lógica de negocio compleja | ❌ Usa código Python normal |

---
## 1. Creación de Arrays

Un **array** de NumPy es como una lista, pero:
- Todos los elementos tienen el **mismo tipo** (int, float, bool…)
- Puede tener múltiples dimensiones (1D, 2D, 3D…)
- Las operaciones matemáticas se aplican a **todos los elementos a la vez**

### 1.1 Desde una lista

In [5]:
# Array 1D — como una fila de datos
notas = np.array([85, 72, 91, 60, 78, 95])

print('Array:', notas)
print('Tipo de datos (dtype):', notas.dtype)  # int64 — todos son enteros
print('Dimensiones (ndim):  ', notas.ndim)    # 1 — una sola dimensión
print('Forma (shape):       ', notas.shape)   # (6,) — 6 elementos
print('Total elementos:     ', notas.size)    # 6

Array: [85 72 91 60 78 95]
Tipo de datos (dtype): int64
Dimensiones (ndim):   1
Forma (shape):        (6,)
Total elementos:      6


In [6]:
# Si mezclas int y float, NumPy convierte todo a float (el tipo más general)
mixto = np.array([1, 2.5, 3, 4.0])
print('Array mixto int/float:', mixto)
print('Dtype resultante:     ', mixto.dtype)  # float64

Array mixto int/float: [1.  2.5 3.  4. ]
Dtype resultante:      float64


In [7]:
# Array 2D — como una tabla (filas y columnas)
# Cada lista interna es una FILA
#
#           Mat  Fís  Quím
califs = np.array([
    [85, 90, 78],   # Estudiante 1
    [72, 88, 95],   # Estudiante 2
    [91, 76, 83],   # Estudiante 3
    [68, 94, 87]    # Estudiante 4
])

print('Tabla de calificaciones:')
print(califs)
print(f'\nShape: {califs.shape}  →  {califs.shape[0]} estudiantes, {califs.shape[1]} materias')

Tabla de calificaciones:
[[85 90 78]
 [72 88 95]
 [91 76 83]
 [68 94 87]]

Shape: (4, 3)  →  4 estudiantes, 3 materias


### 1.2 Funciones de creación

NumPy tiene funciones para crear arrays sin escribir cada valor manualmente.
Son muy útiles para inicializar arrays antes de llenarlos con un ciclo.

In [8]:
# np.zeros: lleno de ceros
# Caso de uso: inicializar un array antes de llenarlo con un ciclo
acumulador = np.zeros(5)
print('Inicializado en ceros:', acumulador)

# Llenarlo con un ciclo
for i in range(5):
    acumulador[i] = (i + 1) ** 2   # cuadrados: 1, 4, 9, 16, 25

print('Después del ciclo:    ', acumulador)

Inicializado en ceros: [0. 0. 0. 0. 0.]
Después del ciclo:     [ 1.  4.  9. 16. 25.]


In [9]:
# np.arange(inicio, fin, paso) — como range() pero devuelve array
# IMPORTANTE: el valor 'fin' NO está incluido

dias = np.arange(1, 8)          # días de la semana
pares = np.arange(0, 20, 2)     # números pares
decimales = np.arange(0, 1.1, 0.25)  # con paso decimal

print('Días (1 al 7):     ', dias)
print('Pares hasta 18:    ', pares)
print('De 0 a 1 en 0.25:  ', decimales)

Días (1 al 7):      [1 2 3 4 5 6 7]
Pares hasta 18:     [ 0  2  4  6  8 10 12 14 16 18]
De 0 a 1 en 0.25:   [0.   0.25 0.5  0.75 1.  ]


In [10]:
# np.linspace(inicio, fin, n_puntos) — n puntos equiespaciados
# A diferencia de arange, AQUÍ SÍ se incluye el fin
# Caso de uso: crear el eje X para graficar una función

x = np.linspace(0, 10, 6)   # 6 puntos equiespaciados entre 0 y 10
print('linspace(0, 10, 6):', x)
print('Distancia entre puntos:', x[1] - x[0])

# Para graficar sen(x), necesitamos muchos puntos (curva suave)
x_fino = np.linspace(0, 2*np.pi, 1000)
print(f'\nPara graficar: {len(x_fino)} puntos entre 0 y 2π')

linspace(0, 10, 6): [ 0.  2.  4.  6.  8. 10.]
Distancia entre puntos: 2.0

Para graficar: 1000 puntos entre 0 y 2π


In [11]:
# Diferencia visual entre arange y linspace
print('arange(0, 1, 0.333):  ', np.arange(0, 1, 1/3).round(3),
      '← puede no incluir el 1.0')
print('linspace(0, 1, 4):    ', np.linspace(0, 1, 4).round(3),
      '← SIEMPRE incluye 0 y 1')

arange(0, 1, 0.333):   [0.    0.333 0.667] ← puede no incluir el 1.0
linspace(0, 1, 4):     [0.    0.333 0.667 1.   ] ← SIEMPRE incluye 0 y 1


### 1.3 Arrays aleatorios

Se usan para:
- **Simulaciones** (simular datos de un experimento)
- **Tests** (probar código con datos de prueba)
- **Estadística** (bootstrap, Monte Carlo)

La `seed` (semilla) hace que los números "aleatorios" sean reproducibles:
si tú y yo usamos la misma semilla, obtenemos los mismos números.

In [12]:
rng = np.random.default_rng(seed=42)  # semilla fija → resultados reproducibles

# Distribución uniforme: cualquier valor entre a y b tiene la misma probabilidad
# Caso de uso: sorteos, asignar grupos aleatoriamente
uniforme = rng.random(6)   # 6 valores entre 0.0 y 1.0
print('Uniforme [0,1):     ', uniforme.round(3))

# Enteros aleatorios
# Caso de uso: simular tiradas de dado, muestras aleatorias
dados = rng.integers(1, 7, size=10)   # 10 tiradas de un dado de 6 caras
print('Tiradas de dado:    ', dados)

# Distribución normal: campana de Gauss (μ=media, σ=desviación estándar)
# Caso de uso: simular alturas, errores de medición, notas de examen
alturas = rng.normal(loc=170, scale=8, size=5)   # media=170cm, std=8cm
print('Alturas simuladas:  ', alturas.round(1))

Uniforme [0,1):      [0.774 0.439 0.859 0.697 0.094 0.976]
Tiradas de dado:     [5 5 5 5 4 1 6 3 4 3]
Alturas simuladas:   [176.2 170.5 179.  173.7 163.1]


In [13]:
# Ejemplo: simular 1000 tiradas de un dado y contar cada resultado
rng2 = np.random.default_rng(0)
tiradas = rng2.integers(1, 7, size=1000)

print('Resultado de 1000 tiradas de dado:')
for cara in range(1, 7):
    conteo = np.sum(tiradas == cara)   # cuántas veces salió este número
    barra  = '█' * (conteo // 10)     # barra proporcional
    print(f'  Cara {cara}: {conteo:4d} veces  {barra}')

print(f'\nTotal tiradas: {len(tiradas)}')
print(f'Esperado por cara: ~{1000//6} veces')

Resultado de 1000 tiradas de dado:
  Cara 1:  151 veces  ███████████████
  Cara 2:  164 veces  ████████████████
  Cara 3:  148 veces  ██████████████
  Cara 4:  182 veces  ██████████████████
  Cara 5:  181 veces  ██████████████████
  Cara 6:  174 veces  █████████████████

Total tiradas: 1000
Esperado por cara: ~166 veces


---
## 2. Indexing y Slicing

"Indexing" = acceder a **un elemento** por su posición.  
"Slicing" = acceder a **un rango** de elementos.

**La regla de los índices negativos:** en Python (y NumPy), el índice `-1` es el último,
`-2` el penúltimo, etc. Es como contar desde el final.

### 2.1 Arrays 1D

In [14]:
#              0     1     2     3     4     5     6
temps = np.array([15.2, 17.8, 20.1, 23.5, 25.0, 22.3, 18.6])
#             -7    -6    -5    -4    -3    -2    -1

print('Array:', temps)
print()
print('Primer elemento    [0]:', temps[0])    # 15.2
print('Último elemento   [-1]:', temps[-1])   # 18.6  ← muy útil
print('Penúltimo         [-2]:', temps[-2])   # 22.3

print()
# Slicing: [inicio:fin:paso]  — fin NO incluido
print('Primeros 3    [0:3]:', temps[0:3])
print('Del 2 al 4    [2:5]:', temps[2:5])
print('Últimos 3     [-3:]:', temps[-3:])
print('De 2 en 2    [::2]:', temps[::2])
print('Invertido    [::-1]:', temps[::-1])

Array: [15.2 17.8 20.1 23.5 25.  22.3 18.6]

Primer elemento    [0]: 15.2
Último elemento   [-1]: 18.6
Penúltimo         [-2]: 22.3

Primeros 3    [0:3]: [15.2 17.8 20.1]
Del 2 al 4    [2:5]: [20.1 23.5 25. ]
Últimos 3     [-3:]: [25.  22.3 18.6]
De 2 en 2    [::2]: [15.2 20.1 25.  18.6]
Invertido    [::-1]: [18.6 22.3 25.  23.5 20.1 17.8 15.2]


In [15]:
# Caso de uso: analizar una serie de temperaturas semanales
temp_semana = np.array([22, 24, 21, 19, 25, 27, 23])   # L M X J V S D
dias_nombre = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom']

print('=== Análisis de temperatura semanal ===')
print(f'Temperatura más alta: {temp_semana.max()}°C el {dias_nombre[np.argmax(temp_semana)]}')
print(f'Temperatura más baja: {temp_semana.min()}°C el {dias_nombre[np.argmin(temp_semana)]}')
print(f'Promedio:             {temp_semana.mean():.1f}°C')

# Días laborales (Lun-Vie) vs fin de semana
laborales  = temp_semana[:5]   # índices 0 al 4
finde      = temp_semana[5:]   # índices 5 y 6
print(f'\nPromedio días laborales:  {laborales.mean():.1f}°C')
print(f'Promedio fin de semana:   {finde.mean():.1f}°C')

=== Análisis de temperatura semanal ===
Temperatura más alta: 27°C el Sáb
Temperatura más baja: 19°C el Jue
Promedio:             23.0°C

Promedio días laborales:  22.2°C
Promedio fin de semana:   25.0°C


### 2.2 Arrays 2D

Para arrays 2D usamos **dos índices separados por coma**: `array[fila, columna]`.
El símbolo `:` significa "todos".

In [16]:
#           Día1  Día2  Día3  Día4  Día5
T = np.array([
    [22, 24, 21, 23, 25],   # Ciudad A (fila 0)
    [15, 16, 14, 17, 15],   # Ciudad B (fila 1)
    [30, 32, 29, 31, 33],   # Ciudad C (fila 2)
    [10, 11,  9, 12, 10]    # Ciudad D (fila 3)
])
ciudades = ['Ciudad A', 'Ciudad B', 'Ciudad C', 'Ciudad D']

print('Tabla de temperaturas:')
print(T)

print('\n--- Acceso por posición ---')
print('Temperatura Ciudad A día 1  [0, 0]:', T[0, 0])   # 22
print('Temperatura Ciudad C día 5  [2, 4]:', T[2, 4])   # 33

print('\n--- Slicing ---')
print('Toda la Ciudad B (fila 1)  [1, :]:', T[1, :])    # fila completa
print('Todas las ciudades, Día 3  [:, 2]:', T[:, 2])    # columna completa
print('Submatriz 2×2 (A,B × días 1,2):')
print(T[0:2, 0:2])

Tabla de temperaturas:
[[22 24 21 23 25]
 [15 16 14 17 15]
 [30 32 29 31 33]
 [10 11  9 12 10]]

--- Acceso por posición ---
Temperatura Ciudad A día 1  [0, 0]: 22
Temperatura Ciudad C día 5  [2, 4]: 33

--- Slicing ---
Toda la Ciudad B (fila 1)  [1, :]: [15 16 14 17 15]
Todas las ciudades, Día 3  [:, 2]: [21 14 29  9]
Submatriz 2×2 (A,B × días 1,2):
[[22 24]
 [15 16]]


In [17]:
# Caso de uso: calcular el promedio de cada ciudad usando axis
# axis=1 → operación a lo largo de las COLUMNAS (promedio de cada fila)
promedios = T.mean(axis=1)

print('Temperatura promedio por ciudad:')
for ciudad, prom in zip(ciudades, promedios):
    print(f'  {ciudad}: {prom:.1f}°C')

print('\nTemperatura promedio por día (axis=0):')
prom_dias = T.mean(axis=0)
for d, p in enumerate(prom_dias, start=1):
    print(f'  Día {d}: {p:.1f}°C')

Temperatura promedio por ciudad:
  Ciudad A: 23.0°C
  Ciudad B: 15.4°C
  Ciudad C: 31.0°C
  Ciudad D: 10.4°C

Temperatura promedio por día (axis=0):
  Día 1: 19.2°C
  Día 2: 20.8°C
  Día 3: 18.2°C
  Día 4: 20.8°C
  Día 5: 20.8°C


### 2.3 Indexing booleano (filtrado)

Esta es una de las técnicas más poderosas de NumPy.
Funciona así:
1. Creas una **condición** → NumPy devuelve un array de `True`/`False`
2. Usas ese array como "máscara" para **seleccionar** solo los elementos `True`

Es como un ciclo `for` con un `if`, pero mucho más rápido.

In [18]:
notas = np.array([45, 72, 88, 34, 91, 60, 55, 78, 95, 42])

# Equivalente al ciclo:
# for nota in notas:
#     if nota >= 60:
#         ...

mascara = notas >= 60
print('Notas:        ', notas)
print('Máscara ≥60:  ', mascara)   # True donde la condición se cumple
print('Aprobados:    ', notas[mascara])
print(f'Cantidad de aprobados: {mascara.sum()} de {len(notas)}')

Notas:         [45 72 88 34 91 60 55 78 95 42]
Máscara ≥60:   [False  True  True False  True  True False  True  True False]
Aprobados:     [72 88 91 60 78 95]
Cantidad de aprobados: 6 de 10


In [19]:
# Múltiples condiciones: & (y), | (o)
# IMPORTANTE: cada condición va entre paréntesis
print('Notas entre 70 y 89:', notas[(notas >= 70) & (notas <= 89)])
print('Reprobados o 100:   ', notas[(notas < 60) | (notas == 100)])

# np.where: versión vectorizada del if/else
# np.where(condición, valor_si_true, valor_si_false)
# Equivalente a: ["Aprobado" if n >= 60 else "Reprobado" for n in notas]
estado = np.where(notas >= 60, 'Aprobado', 'Reprobado')
print('\nEstado de cada nota:')
for nota, est in zip(notas, estado):
    print(f'  {nota:3d} → {est}')

Notas entre 70 y 89: [72 88 78]
Reprobados o 100:    [45 34 55 42]

Estado de cada nota:
   45 → Reprobado
   72 → Aprobado
   88 → Aprobado
   34 → Reprobado
   91 → Aprobado
   60 → Aprobado
   55 → Reprobado
   78 → Aprobado
   95 → Aprobado
   42 → Reprobado


In [20]:
# Modificar valores con indexing booleano
datos = np.array([85, 102, 76, 115, 90, 88, 130, 70])
print('Datos originales:  ', datos)

# Limitar valores al rango [0, 100]: equivale a:
# for i in range(len(datos)):
#     if datos[i] > 100: datos[i] = 100
datos_copia = datos.copy()
datos_copia[datos_copia > 100] = 100
print('Datos limitados:   ', datos_copia)

# np.clip hace lo mismo de forma más limpia
print('Con np.clip:       ', np.clip(datos, 0, 100))

Datos originales:   [ 85 102  76 115  90  88 130  70]
Datos limitados:    [ 85 100  76 100  90  88 100  70]
Con np.clip:        [ 85 100  76 100  90  88 100  70]


---
## 3. Operaciones Matemáticas

### 3.1 Operaciones elemento a elemento

Cuando aplicas `+`, `-`, `*`, `/` entre dos arrays del mismo tamaño,
NumPy lo hace **elemento a elemento**. Esto reemplaza ciclos `for` comunes.


In [21]:
precios    = np.array([100.0, 250.0, 80.0, 320.0, 60.0])
cantidades = np.array([3,     2,     5,    1,     10   ])

# Calcular el total de cada producto
# Equivalente a: [p * q for p, q in zip(precios, cantidades)]
totales = precios * cantidades

print('Precios:    ', precios)
print('Cantidades: ', cantidades)
print('Totales:    ', totales)
print(f'\nTotal general: Q{totales.sum():,.2f}')
print(f'Producto más caro total: Q{totales.max():.2f}')

Precios:     [100. 250.  80. 320.  60.]
Cantidades:  [ 3  2  5  1 10]
Totales:     [300. 500. 400. 320. 600.]

Total general: Q2,120.00
Producto más caro total: Q600.00


In [22]:
# Operación con escalar: se aplica a TODOS los elementos
# Caso de uso: aplicar un descuento del 15% a todos los precios
precios_con_descuento = precios * (1 - 0.15)
ahorro = precios - precios_con_descuento

print('Precio original:    ', precios)
print('Precio con -15%:    ', precios_con_descuento)
print('Ahorro:             ', ahorro.round(2))

Precio original:     [100. 250.  80. 320.  60.]
Precio con -15%:     [ 85.  212.5  68.  272.   51. ]
Ahorro:              [15.  37.5 12.  48.   9. ]


### 3.2 Broadcasting — operaciones entre arrays de distinto tamaño

NumPy puede operar arrays de formas distintas siguiendo reglas automáticas.
La regla básica: el array más pequeño se "expande" para coincidir con el grande.

In [23]:
# Tabla de ventas: 3 vendedores × 4 meses
ventas = np.array([
    [1200, 1500, 1100, 1800],   # Vendedor A
    [ 900, 1200,  950, 1100],   # Vendedor B
    [1500, 1800, 1400, 2000]    # Vendedor C
])

# Meta mensual distinta cada mes (vector de 4 elementos)
meta = np.array([1000, 1300, 1000, 1500])

# ¿Cuánto superó cada vendedor la meta cada mes?
# Broadcasting: meta (4,) se aplica a cada fila de ventas (3,4)
diferencia = ventas - meta

print('Ventas:')
print(ventas)
print('\nDiferencia respecto a la meta (+ = superó, - = no llegó):')
print(diferencia)

print('\n¿Cada vendedor cumplió la meta cada mes?')
print(ventas >= meta)

Ventas:
[[1200 1500 1100 1800]
 [ 900 1200  950 1100]
 [1500 1800 1400 2000]]

Diferencia respecto a la meta (+ = superó, - = no llegó):
[[ 200  200  100  300]
 [-100 -100  -50 -400]
 [ 500  500  400  500]]

¿Cada vendedor cumplió la meta cada mes?
[[ True  True  True  True]
 [False False False False]
 [ True  True  True  True]]


### 3.3 Funciones matemáticas (ufuncs)

NumPy tiene versiones vectorizadas de funciones matemáticas que actúan sobre
todos los elementos de un array a la vez.

In [24]:
# Caso de uso: calcular la hipotenusa de varios triángulos a la vez
# hipotenusa = sqrt(a² + b²)
a = np.array([3, 5, 8, 12, 7])
b = np.array([4, 12, 6, 5, 24])

hipotenusa = np.sqrt(a**2 + b**2)
print('Cateto a:', a)
print('Cateto b:', b)
print('Hipotenusa:', hipotenusa)

Cateto a: [ 3  5  8 12  7]
Cateto b: [ 4 12  6  5 24]
Hipotenusa: [ 5. 13. 10. 13. 25.]


In [25]:
# Función seno para graficar una onda
# Los ángulos en NumPy siempre van en RADIANES (no grados)
# Para convertir: rad = grados * π/180

angulos_grados = np.array([0, 30, 45, 60, 90, 120, 180, 270, 360])
angulos_rad    = angulos_grados * np.pi / 180

print('Grados  Radianes   sin      cos')
print('-' * 40)
for g, r in zip(angulos_grados, angulos_rad):
    print(f'{g:6d}   {r:7.4f}   {np.sin(r):6.3f}   {np.cos(r):6.3f}')

Grados  Radianes   sin      cos
----------------------------------------
     0    0.0000    0.000    1.000
    30    0.5236    0.500    0.866
    45    0.7854    0.707    0.707
    60    1.0472    0.866    0.500
    90    1.5708    1.000    0.000
   120    2.0944    0.866   -0.500
   180    3.1416    0.000   -1.000
   270    4.7124   -1.000   -0.000
   360    6.2832   -0.000    1.000


---
## 4. Estadísticas

NumPy tiene funciones estadísticas muy eficientes. El parámetro `axis` controla
si la operación va **por columnas** (`axis=0`) o **por filas** (`axis=1`).

In [26]:
rng = np.random.default_rng(7)
notas = rng.integers(50, 101, size=30)   # 30 notas entre 50 y 100

print('Notas:')
print(notas)
print()

# Estadísticos básicos
stats = [
    ('Cantidad',         len(notas)),
    ('Media',            np.mean(notas)),
    ('Mediana',          np.median(notas)),
    ('Desv. estándar',   np.std(notas)),
    ('Mínimo',           np.min(notas)),
    ('Máximo',           np.max(notas)),
    ('Q1 (25%)',         np.percentile(notas, 25)),
    ('Q3 (75%)',         np.percentile(notas, 75)),
]

for nombre, valor in stats:
    print(f'  {nombre:<20}: {valor:.2f}' if isinstance(valor, float) else
          f'  {nombre:<20}: {valor}')

Notas:
[ 98  81  84  95  79  89  92  61  52  65  64  94  96  50  75  91  56  90
  56  73  91  65  67  64  86  62 100  72  74  75]

  Cantidad            : 30
  Media               : 76.57
  Mediana             : 75.00
  Desv. estándar      : 14.74
  Mínimo              : 50
  Máximo              : 100
  Q1 (25%)            : 64.25
  Q3 (75%)            : 90.75


In [27]:
# Estadísticas con axis en una matriz
# Notas de 4 estudiantes en 3 exámenes
#              Examen1  Examen2  Examen3
notas_mat = np.array([
    [75, 82, 90],   # Est. 1
    [60, 70, 65],   # Est. 2
    [95, 88, 92],   # Est. 3
    [80, 76, 84]    # Est. 4
])

# axis=1: promedio de cada estudiante (a lo largo de los exámenes)
prom_estud = notas_mat.mean(axis=1)
# axis=0: promedio de cada examen (a lo largo de los estudiantes)
prom_exam  = notas_mat.mean(axis=0)

print('Promedio por estudiante:')
for i, p in enumerate(prom_estud, 1):
    estado = 'Aprobado' if p >= 70 else 'Reprobado'
    print(f'  Est. {i}: {p:.1f} → {estado}')

print('\nPromedio por examen:')
for i, p in enumerate(prom_exam, 1):
    print(f'  Examen {i}: {p:.1f}')

Promedio por estudiante:
  Est. 1: 82.3 → Aprobado
  Est. 2: 65.0 → Reprobado
  Est. 3: 91.7 → Aprobado
  Est. 4: 80.0 → Aprobado

Promedio por examen:
  Examen 1: 77.5
  Examen 2: 79.0
  Examen 3: 82.8


---
## 5. Reshape — Cambiar la forma

`reshape` reorganiza los elementos en una nueva forma **sin copiarlos**.
El número total de elementos debe ser el mismo.

**Casos de uso:**
- Transformar datos 1D en una tabla 2D
- Preparar datos para modelos de Machine Learning (que esperan formas específicas)

In [28]:
# Imagina que recibes datos de temperatura de 12 meses de forma lineal
temp_anual = np.array([22,19,21,24,27,30,31,30,28,25,22,19])
meses = ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']

print('Datos originales (1D):', temp_anual)

# Reorganizar en 4 trimestres × 3 meses
trimestres = temp_anual.reshape(4, 3)
print('\nPor trimestres (4×3):')
for i, trimestre in enumerate(trimestres, 1):
    print(f'  T{i}: {trimestre}  → promedio: {trimestre.mean():.1f}°C')

Datos originales (1D): [22 19 21 24 27 30 31 30 28 25 22 19]

Por trimestres (4×3):
  T1: [22 19 21]  → promedio: 20.7°C
  T2: [24 27 30]  → promedio: 27.0°C
  T3: [31 30 28]  → promedio: 29.7°C
  T4: [25 22 19]  → promedio: 22.0°C


In [29]:
# -1 le dice a NumPy: "calcula tú esta dimensión"
v = np.arange(1, 13)
print('Original (12 elementos):', v)
print('reshape(3, -1):')
print(v.reshape(3, -1))   # NumPy calcula: 12/3 = 4 columnas
print('reshape(-1, 6):')
print(v.reshape(-1, 6))   # NumPy calcula: 12/6 = 2 filas

Original (12 elementos): [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshape(3, -1):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
reshape(-1, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


---
## 6. Álgebra Lineal

El módulo `np.linalg` implementa operaciones de álgebra lineal.

**Atención:** `A * B` es multiplicación **elemento a elemento** (no es el producto matricial).  
Para el producto matricial usa `A @ B` o `np.matmul(A, B)`.

In [30]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print('A:')
print(A)
print('B:')
print(B)
print()
print('A * B  (elemento a elemento — NO es producto matricial):')
print(A * B)
print()
print('A @ B  (producto MATRICIAL — esto es álgebra lineal):')
print(A @ B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]

A * B  (elemento a elemento — NO es producto matricial):
[[ 5 12]
 [21 32]]

A @ B  (producto MATRICIAL — esto es álgebra lineal):
[[19 22]
 [43 50]]


In [31]:
# Caso de uso: resolver un sistema de ecuaciones
#
# Un estudiante compra 2 lápices y 3 cuadernos y paga Q17.
# Otro estudiante compra 4 lápices y 1 cuaderno y paga Q11.
# ¿Cuánto cuesta cada lápiz y cada cuaderno?
#
# Sistema de ecuaciones:
#   2x + 3y = 17
#   4x + 1y = 11

A = np.array([[2, 3],   # coeficientes
              [4, 1]])
b = np.array([17, 11])  # resultados

solucion = np.linalg.solve(A, b)
print(f'Precio del lápiz:   Q{solucion[0]:.2f}')
print(f'Precio del cuaderno: Q{solucion[1]:.2f}')

# Verificar: A @ solucion debe dar b
print(f'\nVerificación: A @ x = {A @ solucion}  (debe ser {b})')

Precio del lápiz:   Q1.60
Precio del cuaderno: Q4.60

Verificación: A @ x = [17. 11.]  (debe ser [17 11])


---
## 7. Funciones Útiles con Ciclos

A veces necesitamos combinar NumPy con ciclos `for` para lógica más compleja.

In [32]:
# np.argsort devuelve los ÍNDICES que ordenarían el array
# Caso de uso: encontrar el ranking de estudiantes por nota

nombres = np.array(['Ana', 'Luis', 'María', 'Carlos', 'Sofía', 'Pedro'])
notas   = np.array([78, 91, 65, 88, 95, 72])

# argsort en orden descendente (nota más alta = puesto 1)
ranking_indices = np.argsort(notas)[::-1]  # ::-1 invierte

print('=== Ranking de notas ===')
for puesto, idx in enumerate(ranking_indices, start=1):
    print(f'  #{puesto}  {nombres[idx]:<8}  {notas[idx]} puntos')

=== Ranking de notas ===
  #1  Sofía     95 puntos
  #2  Luis      91 puntos
  #3  Carlos    88 puntos
  #4  Ana       78 puntos
  #5  Pedro     72 puntos
  #6  María     65 puntos


In [33]:
# np.unique: valores únicos y su frecuencia
# Caso de uso: contar cuántos estudiantes hay por zona
zonas = np.array([1, 3, 1, 2, 5, 3, 1, 2, 1, 7, 3, 5, 2, 1, 3])

valores_unicos, conteos = np.unique(zonas, return_counts=True)

print('Distribución de estudiantes por zona:')
for zona, conteo in zip(valores_unicos, conteos):
    barra = '▓' * conteo
    print(f'  Zona {zona}: {conteo} estudiantes  {barra}')

Distribución de estudiantes por zona:
  Zona 1: 5 estudiantes  ▓▓▓▓▓
  Zona 2: 3 estudiantes  ▓▓▓
  Zona 3: 4 estudiantes  ▓▓▓▓
  Zona 5: 2 estudiantes  ▓▓
  Zona 7: 1 estudiantes  ▓


---
## 8. Normalización y Estandarización

Dos técnicas fundamentales antes de hacer cálculos o Machine Learning.

**Normalización Min-Max:** escala los datos al rango [0, 1]
$$x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

**Estandarización Z-score:** media=0, desviación estándar=1
$$z = \frac{x - \mu}{\sigma}$$

In [34]:
# Queremos comparar alturas (cm) y pesos (kg) de estudiantes
# No podemos compararlos directamente porque tienen escalas distintas
alturas = np.array([165, 170, 175, 160, 180, 155, 172])
pesos   = np.array([ 60,  70,  80,  55,  85,  50,  75])

# Normalización Min-Max
def normalizar(x):
    return (x - x.min()) / (x.max() - x.min())

# Estandarización Z-score
def estandarizar(x):
    return (x - x.mean()) / x.std()

alt_norm = normalizar(alturas)
pes_norm = normalizar(pesos)

print('Datos originales y normalizados:')
print(f'{"Altura":>8} {"Peso":>6} {"Alt_norm":>10} {"Pes_norm":>10}')
print('-' * 40)
for a, p, an, pn in zip(alturas, pesos, alt_norm, pes_norm):
    print(f'{a:8d} {p:6d} {an:10.3f} {pn:10.3f}')

Datos originales y normalizados:
  Altura   Peso   Alt_norm   Pes_norm
----------------------------------------
     165     60      0.400      0.286
     170     70      0.600      0.571
     175     80      0.800      0.857
     160     55      0.200      0.143
     180     85      1.000      1.000
     155     50      0.000      0.000
     172     75      0.680      0.714


---
## 🏋️ Ejercicio 1: Análisis de Precipitaciones

Se tienen los datos de precipitación (en mm) de una ciudad durante los 12 meses del año:

```
[12, 18, 35, 80, 120, 180, 210, 195, 140, 75, 30, 15]
```

**Tareas:**
1. Identifica los meses con precipitación mayor a 100 mm (temporada lluviosa)
2. Calcula el promedio de precipitación en temporada lluviosa vs. seca
3. Normaliza los datos al rango [0, 1]
4. Imprime un reporte usando un ciclo `for`

*Intenta resolverlo antes de ver la solución.*

In [35]:
# Datos del ejercicio
meses_nombres = ['Ene','Feb','Mar','Abr','May','Jun',
                 'Jul','Ago','Sep','Oct','Nov','Dic']
lluvia = np.array([12, 18, 35, 80, 120, 180, 210, 195, 140, 75, 30, 15])

# Tu solución aquí:

# --- 1. Máscara de temporada lluviosa (> 100 mm) ---
lluviosa = lluvia > 100

# --- 2. Promedios ---
prom_lluviosa = lluvia[lluviosa].mean()
prom_seca     = lluvia[~lluviosa].mean()  # ~ es la negación booleana

# --- 3. Normalización ---
lluvia_norm = (lluvia - lluvia.min()) / (lluvia.max() - lluvia.min())

# --- 4. Reporte ---
print('=== Reporte de Precipitaciones ===')
print(f'{"Mes":<5} {"mm":>6} {"Norm":>6} {"Temporada":<12}')
print('-' * 35)
for mes, mm, norm, es_lluviosa in zip(meses_nombres, lluvia, lluvia_norm, lluviosa):
    temporada = '🌧 Lluviosa' if es_lluviosa else '☀ Seca'
    print(f'{mes:<5} {mm:>6} mm  {norm:>5.2f}  {temporada}')

print(f'\nPromedio temporada lluviosa: {prom_lluviosa:.1f} mm')
print(f'Promedio temporada seca:     {prom_seca:.1f} mm')
print(f'Diferencia: {prom_lluviosa - prom_seca:.1f} mm')

=== Reporte de Precipitaciones ===
Mes       mm   Norm Temporada   
-----------------------------------
Ene       12 mm   0.00  ☀ Seca
Feb       18 mm   0.03  ☀ Seca
Mar       35 mm   0.12  ☀ Seca
Abr       80 mm   0.34  ☀ Seca
May      120 mm   0.55  🌧 Lluviosa
Jun      180 mm   0.85  🌧 Lluviosa
Jul      210 mm   1.00  🌧 Lluviosa
Ago      195 mm   0.92  🌧 Lluviosa
Sep      140 mm   0.65  🌧 Lluviosa
Oct       75 mm   0.32  ☀ Seca
Nov       30 mm   0.09  ☀ Seca
Dic       15 mm   0.02  ☀ Seca

Promedio temporada lluviosa: 169.0 mm
Promedio temporada seca:     37.9 mm
Diferencia: 131.1 mm


---
## 🏋️ Ejercicio 2: Simulación de Calificaciones

Simula las calificaciones de un curso con 40 estudiantes en 4 exámenes.

**Tareas:**
1. Genera los datos con `rng.integers(50, 101, size=(40, 4))`
2. Calcula el promedio de cada estudiante
3. Asigna letra: A (≥90), B (≥80), C (≥70), D (≥60), F (<60)
4. Imprime cuántos estudiantes hay con cada letra
5. Imprime el promedio del examen más difícil (el de menor promedio)


In [36]:
rng = np.random.default_rng(2025)

# 1. Generar datos
examenes = rng.integers(50, 101, size=(40, 4)).astype(float)

# 2. Promedio por estudiante (axis=1: a lo largo de los exámenes)
promedios = examenes.mean(axis=1)

# 3. Asignar letra con ciclo for y condicionales
def asignar_letra(prom):
    if prom >= 90:
        return 'A'
    elif prom >= 80:
        return 'B'
    elif prom >= 70:
        return 'C'
    elif prom >= 60:
        return 'D'
    else:
        return 'F'

letras = np.array([asignar_letra(p) for p in promedios])

# 4. Conteo por letra
print('=== Distribución de calificaciones ===')
for letra in ['A', 'B', 'C', 'D', 'F']:
    conteo  = np.sum(letras == letra)
    pct     = conteo / len(letras) * 100
    barra   = '█' * conteo
    print(f'  {letra}: {conteo:2d} estudiantes ({pct:4.1f}%)  {barra}')

# 5. Examen más difícil
prom_examenes = examenes.mean(axis=0)  # promedio de cada examen
idx_dificil   = np.argmin(prom_examenes)
print(f'\nPromedios por examen: {prom_examenes.round(1)}')
print(f'Examen más difícil: Examen {idx_dificil+1} (promedio: {prom_examenes[idx_dificil]:.1f})')

=== Distribución de calificaciones ===
  A:  3 estudiantes ( 7.5%)  ███
  B: 10 estudiantes (25.0%)  ██████████
  C: 16 estudiantes (40.0%)  ████████████████
  D: 11 estudiantes (27.5%)  ███████████
  F:  0 estudiantes ( 0.0%)  

Promedios por examen: [74.4 77.1 75.6 78.2]
Examen más difícil: Examen 1 (promedio: 74.5)
